controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    position_controller:  # 控制器名字
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:  # 关节状态发布器
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
gains:
      joint1:
        p: 100.0
        i: 0.0
        d: 5.0
        
joint_state_broadcaster:
  ros__parameters:
    use_urdf_to_filter: true
